---
apiVersion: openslo/v1
kind: SLO
metadata:
  displayName: Mr Telemetry App Latency
  name: mr-telemetry-app-latency
  project: build-on-aws
spec:
  description: Latency SLO for Mr Telemetry
  service: build-on-aws-service
  indicator:
    metadata:
      name: mr-telemetry-latency-indicator
      displayName: Mr Telemetry Latency Indicator
    spec:
      thresholdMetric:
        metricSource:
          type: AmazonPrometheus
          spec:
            promql: histogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket[1m])) by (le))
  timeWindow:
    - duration: 28d
      isRolling: true
  budgetingMethod: Occurrences
  objectives:
    - displayName: Good
      target: 0.98
      value: 1.9
      op: lt
